version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER_NAME}
    hostname: ${REDIS_HOST_NAME}
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 30
    restart: unless-stopped
